### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by mattncsu** [loboris/ESP32_ePaper_example#1]
Very cool library with a lot of impressive features!  I'm looking forward to trying it on the ESP32 I just received.  In the meantime, I'm working on a project interfacing an ESP8266 with the same Waveshare 2.9" EPD.  Do you know of a similar library that would work with the 8266 or could this one be ported in the future?

**Comment by AtomDrug** [comment]
It should work with any controller which has SPI.
Depending on the controller it will be neccessary to configure the SPI properly.

**Comment by mattncsu** [comment]
Thanks! I'll give it a go. I wasn't sure if there were ESP32 specific items in the code.
