### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by DavidEnds** [loboris/ESP32_ePaper_example#2]
It is compatible with the arduino IDE?

**Comment by AtomDrug** [comment]
Well basically it should work.
It depends if you want to use the Arduino SPI Library then you need to replace the SPI stuff currently in here.
Also the other librarys used might need adjustments or you get rid of them.

Currently also porting this to Arduino with PlatformIO, cause this is by far the best API for EPD that i´ve seen yet.
Awesome work loboris!

**Comment by mattncsu** [comment]
@AtomDrug keep us posted, would love to see an Arduino port!

**Comment by AtomDrug** [comment]
@mattncsu here you go: https://github.com/AtomDrug/ESP32_ePaper_example
it is not perfect but works quite well so far.

**Comment by mattncsu** [comment]
@AtomDrug Thanks for posting, can't wait to try it out on an ESP8266 based project I'm working on now!
