### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by habkorn** [loboris/ESP32_ePaper_example#3]
Hi,
when trying to build I'm getting the message

In file included from C:/msys32/home/tomhab/esp/esp-idf/components/fatfs/src/diskio_spiflash.c:20:0:
C:/msys32/home/tomhab/esp/esp-idf/components/fatfs/src/diskio_spiflash.h:23:28: fatal error: wear_levelling.h: No such file or directory
compilation terminated.

How to fix this issue? Thanks!

**Comment by loboris** [comment]
The repository is updated, please pill the changes and try again.

**Comment by xbenng** [comment]
i'm still having this issue.
