### ISSUE TITLE
Make all errors

### ISSUE THREAD

**Issue by fhng** [loboris/ESP32_ePaper_example#4]
Updated ESP-IDF by running git pull and now Make all is giving me these errors.
.......
.......
CC build/spiffs/esp_spiffs.o
CC build/spiffs/list.o
CC build/spiffs/mutex.o
CC build/spiffs/spiffs_cache.o
CC build/spiffs/spiffs_check.o
CC build/spiffs/spiffs_gc.o
CC build/spiffs/spiffs_hydrogen.o
CC build/spiffs/spiffs_nucleus.o
CC build/spiffs/spiffs_vfs.o
/Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c: In function 'vfs_spiffs_register':
/Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c:826:9: error: unknown field 'fd_offset' specified in initializer
         .fd_offset = 0,
         ^
In file included from /Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c:24:0:
/Users/lighflares/esp/esp-idf/components/vfs/include/esp_vfs.h:39:37: warning: initialized field overwritten [-Woverride-init]
 #define ESP_VFS_FLAG_DEFAULT        0
                                     ^
/Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c:827:18: note: in expansion of macro 'ESP_VFS_FLAG_DEFAULT'
         .flags = ESP_VFS_FLAG_DEFAULT,
                  ^
/Users/lighflares/esp/esp-idf/components/vfs/include/esp_vfs.h:39:37: note: (near initialization for 'vfs.flags')
 #define ESP_VFS_FLAG_DEFAULT        0
                                     ^
/Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c:827:18: note: in expansion of macro 'ESP_VFS_FLAG_DEFAULT'
         .flags = ESP_VFS_FLAG_DEFAULT,
                  ^
/Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c:828:18: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
         .write = &vfs_spiffs_write,
                  ^
/Users/lighflares/esp/ESP32_ePaper_example/components/spiffs/./spiffs_vfs.c:828:18: note: (near initialization for 'vfs.<anonymous>.write')
make[1]: *** [spiffs_vfs.o] Error 1
make: *** [component-spiffs-build] Error 2

**Comment by fhng** [comment]
Fixed, I comment it out.
File spiffs_vfs.c, 

`void vfs_spiffs_register() {

        if (spiffs_is_registered) return;

        esp_vfs_t vfs = {
        //.fd_offset = 0,
        .flags = ESP_VFS_FLAG_DEFAULT,
        .write = &vfs_spiffs_write,
        .open = &vfs_spiffs_open,
        .fstat = &vfs_spiffs_fstat,
        .close = &vfs_spiffs_close,
        .read = &vfs_spiffs_read,
        .lseek = &vfs_spiffs_lseek,
        .stat = &vfs_spiffs_stat,
        .link = NULL,
        .unlink = &vfs_spiffs_unlink,
        .rename = &vfs_spiffs_rename,
                .mkdir = &vfs_spiffs_mkdir,
                .opendir = &vfs_spiffs_opendir,
                .readdir = &vfs_spiffs_readdir,
                .closedir = &vfs_piffs_closedir,
    };

`

**Comment by loboris** [comment]
Fixed in latest commit.
